---
name: Date-Holidays-Super
version: 0.03
author:
  - 'Jonas B. Nielsen, <jonasbn@cpan.org>'
abstract: a SUPER class for the Date::Holidays::* modules
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::Harness: 0
  Test::More: 0
provides:
  Date::Holidays::Super:
    file: lib/Date/Holidays/Super.pm
    version: 0.03
no_index:
  directory:
    - t
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
