#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Date-Holidays-Super
version:      0.01
version_from: lib/Date/Holidays/Super.pm
installdirs:  site
requires:
    File::Find:                    0
    Test::Pod::Coverage:           0.08
    File::Spec:                    0
    Test::More:                    0
    Test::Pod:                     0.95

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
