name: CI Action
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Continuous Integration
        uses: jonasbn/ebirah@v0.4.0
      - name: ebirah test
        run: docker run --rm --volume $PWD:/tmp jonasbn/ebirah test
